#! /bin/bash

filename=$1

yacc -d $filename.y 
if [ $? -ne 0 ]; then
    exit $?
fi

lex $filename.l
if [ $? -ne 0 ]; then
    exit $?
fi

gcc y.tab.c lex.yy.c -o $filename

if [ $? -ne 0 ]; then
    exit $?
fi 


"./$filename"